kind: pipeline
name: Surya_kramel

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: setup&kramel
    image: starlight2834/ci_docker:latest
    environment:
      TOKEN:
        from_secret: token
      CHAT_ID:
        from_secret: chat_id
    commands:
      - apt update && apt-get install -y build-essential bc python curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev clang flex bison cpio
      - bash kramel.sh
